import typer
import os
from rich.console import Console
from rich.table import Table
from aim_cli.config import load_config, save_config, RepoConfig

app = typer.Typer()
console = Console()

@app.command()
def create(
    name: str = typer.Argument(..., help="Name of the repository to create"),
    type: str = typer.Option(..., help="Type of storage: 'local' or 's3'"),
    path: str = typer.Option(..., help="Path or URL for the storage"),
    region: str = typer.Option(None, help="AWS Region (for S3 only)"),
    access_key: str = typer.Option(None, help="AWS Access Key (for S3 only)"),
    secret_key: str = typer.Option(None, help="AWS Secret Key (for S3 only)"),
    username: str = typer.Option(None, help="Username (for SFTP)"),
    password: str = typer.Option(None, help="Password (for SFTP)"),
):
    """Register a new model repository."""
    if type not in ["local", "s3", "sftp"]:
        console.print(f"[bold red]Error:[/bold red] Invalid type '{type}'. Must be 'local', 's3', or 'sftp'.")

        raise typer.Exit(code=1)


    if type == "sftp" and not password:
        password = typer.prompt("SFTP Password", hide_input=True)

    config = load_config()
    if config.get_repo(name):
        console.print(f"[bold red]Error:[/bold red] Repo '{name}' already exists.")
        raise typer.Exit(code=1)

    new_repo = RepoConfig(
        name=name,
        type=type,
        path=path,
        region=region,
        access_key=access_key,
        secret_key=secret_key,
        username=username,
        password=password
    )
    
    config.add_repo(new_repo)
    save_config(config)

    # Handle secrets storage in .env
    secrets_to_store = {}
    normalized_name = name.upper().replace("-", "_")
    
    if password:
        secrets_to_store[f"AIM_REPO_{normalized_name}_PASSWORD"] = password
    if secret_key:
        secrets_to_store[f"AIM_REPO_{normalized_name}_SECRET_KEY"] = secret_key
    if access_key:
        secrets_to_store[f"AIM_REPO_{normalized_name}_ACCESS_KEY"] = access_key

    if secrets_to_store:
        env_path = ".env"
        # Check if .env exists
        if not os.path.exists(env_path):
            with open(env_path, "w") as f:
                f.write(f"# Auto-generated by aim_cli (Repo: {name})\n")
        
        # Validate if key already exists or append
        # For simplicity in this prompt-based agent, we just append or warn.
        # But appending is safer than overwriting the whole file.
        # Let's read existing lines first to avoid duplicates
        with open(env_path, "r") as f:
            existing_lines = f.readlines()
        
        with open(env_path, "a") as f:
            for key, value in secrets_to_store.items():
                already_exists = any(line.strip().startswith(f"{key}=") for line in existing_lines)
                if not already_exists:
                    f.write(f"{key}=\"{value}\"\n")
                    console.print(f"[yellow]Added {key} to .env[/yellow]")
                else:
                    console.print(f"[yellow]Warning: {key} already exists in .env. Please update it manually if needed.[/yellow]")

    console.print(f"[green]Repo '{name}' created successfully![/green]")

@app.command("list")
def list_repos():
    """List all registered repositories."""
    config = load_config()
    if not config.repos:
        console.print("No repositories found.")
        return

    table = Table(title="Model Repositories")
    table.add_column("Name", style="cyan")
    table.add_column("Type", style="magenta")
    table.add_column("Path", style="green")

    for repo in config.repos:
        table.add_row(repo.name, repo.type, repo.path)
    
    console.print(table)

@app.command()
def delete(name: str):
    """Unregister a repository."""
    config = load_config()
    if config.remove_repo(name):
        save_config(config)
        console.print(f"[green]Repo '{name}' deleted.[/green]")
    else:
        console.print(f"[red]Repo '{name}' not found.[/red]")
